### ISSUE TITLE
Can't create new version from withdrawn version

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1054]
# Bug Report

## Description

If a work has a version history like this:
- v1: published
- v2: withrdawn

 ... when creating a new draft (v3), it will be based on v1 instead of v2.

## To Reproduce

1. Create a new work with a version history as above
2. Create a draft
3. The draft will be based on the published version, not the withdrawn version

## Expected behavior
The draft should be based on the most recent version even if it's withdrawn.

**Comment by awead** [comment]
@srerickson While we can do this, I think there's a bit of a conceptual conflict here. With the changes that were done in #1010 and #1026, in the scenario described above, version 1 becomes the de facto representative version. This means that it's the one that is indexed, and the one that the user will see on their dashboard and public search results. In that sense, it might be weird that a new version would come from a version that isn't obvious to them, even though the withdrawn version is newer.

If I were to liken this with git, withdrawing a version is comparable to a revert. When a commit is reverted, the "latest" state of the repo is the commit just before the commit that was reverted, aka. version 1. 

Side note, if you look at version 2 here, there's the message:

> This is an older version of the work. View the current version.

So we might want to revisit this messaging.

Another idea is that we not think of versions as numerically ordered, and in this case, version 1 appears before version 2 in the listing.

**Comment by awead** [comment]
UPDATE:

So the UI is saying one thing, the code is doing the other. The UI button says it's creating a new version from V1, but the code is actually creating the version from the _latest_ version, or v2. Here is the conceptual conflict born out. At this point, it makes more sense to me to create the new version from the representative version (v1) because that's consistent with the rest of the system. Creating the new version from the latest version might also require changing the messaging because looking at v2, it looks like it's not the current version, and that might confuse people.

**Comment by srerickson** [comment]
As part of #1065, we're considering simplifying the buttons on the blue bar; the changes may address the concerns above. The idea is to replace the two buttons ("create draft from v" and  "edit v") with a button that always takes you to the form for the draft regardless of the version you're looking at.
