### ISSUE TITLE
Preview draft button

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#1079]
Remove the "An updated draft version for this work is available" message that appears on resources with draft versions available and have a button instead.

## WDLL

* Button next to the edit/create button in blue bar
* Button states: "Preview" with tooltip
* Button only appears if a draft is available to user

**Comment by nicktiberi** [comment]
@srerickson - since we will still have the ability to view a draft via the version navigation on the right side, do we still want a "Preview Draft" button? 

I think originally we assumed we needed a special way to preview the draft because we were getting rid of the dropdown version nav in the blue bar.

If we don't need it, then maybe this ticket just becomes removing the "An updated draft version for this work is available" message.

**Comment by srerickson** [comment]
@nicktiberi  - Let's try it without the preview button, as you suggest.
