### ISSUE TITLE
API should accept orcids with dashes

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#1108]
# Bug Report

## Description

When using the API to create a new work, if a creator is added with an orcid, the request will fail if the orcid has dashes, ex: `1234-1234-1234-123X`. This is due to a discrepancy between the UI and the API. We validate and store Orcids in the database _without_ their dashes. In the UI, we allow the user to enter them via an input mask, but they're sent to the controller without any dashes.

Because API inputs are passed on to the application without any changes, the error can crop up.

## To Reproduce

1. Submit a new work to the API using any Orcid without the dashes.

## Expected behavior

API submissions should just work, whether or not the orcid has dashes or not.

**Comment by nicktiberi** [comment]
@srerickson - Ryan and I tested the ingest API endpoint (`POST api/v1/ingest`) with your Orcid with and without dashes, and both worked, so it seems like this was fixed at some point after this issue was opened.

The underlying code is using the `OrcidId` class which sanitizes the Orcid input by the API user:
https://github.com/psu-libraries/scholarsphere/blob/develop/app/models/orcid_id.rb#L16

Please let me know if you'd like me to check anything else out here, but this seems to be working properly.

**Comment by nicktiberi** [comment]
Closing since this seems to be working properly and the Orcid sanitization functionality is tested.
