### ISSUE TITLE
Admins not able to add any work to a collection

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1150]
# Bug Report

## Description
With admin privileges, a user should be able to add any work to any collection, but this isn't the case. Specifically, not all works are findable in the "Add works to collection" form. The drop-down list of works is quite long, but it doesn't include everything. I'm not sure how it is scoped. 

## To Reproduce
1. Enable admin privileges
2. Find a collection to update ([for example](https://scholarsphere-qa.dsrd.libraries.psu.edu/resources/e52091de-ccdd-40b8-8a8b-26a8e4c1430a))
3. On the "add works to collection" form, search for a work that exists (for example: "[Building a Community of Curatorial Practice at Penn State: A Case Study](https://scholarsphere-qa.dsrd.libraries.psu.edu/resources/67744923-b5f4-4beb-8c61-588b9c09daa3)")
4. A work called "Preview of Building a Community of Curatorial Practice at Penn State" is found, but that's not the intended work.

## Expected behavior

With admin privileges, a user should be able to add any work to any collection. *More generally, a user can add a work to a collection if they have edit permissions for both the work and the collection.*

**Comment by awead** [comment]
@srerickson I can do this if I have edit access to both collection and the work. I suspect the issue is that `Dashboard::MemberWorksSearchBuilder` is not honoring the user's admin permissions. It also might be a bit more pervasive that than, as I also saw some Stimulus-related js errors in the console when I tried to and the "Preview ..." work to the collection when I did have admin privileges enabled.

**Comment by srerickson** [comment]
One approach here is to re-architect the search UI for adding works to collections

**Comment by awead** [comment]
Ok, I've verified that the permissions are behaving correctly. If I set this up locally, as I an admin, I can see all the published works in the collection form. The reason why they're not showing up in production is that the controller for the form is capping the total number of documents at 10K:

https://github.com/psu-libraries/scholarsphere/blob/develop/app/controllers/dashboard/form/members_controller.rb#L43

Currently, there are over 11K works; however, only ~9K are published. So why are we still running up against the 10K limit? I think the reason here is that SearchBuilder classes apply a set of filter queries to the initial result set, whittling them down into the set of documents that fit our criteria, i.e. permissions, publication status, etc. What's probably happening is that the initial set of works is capped at 10K and includes a mix of published and unpublished works. When the filters are applied, it filtering out the ineligible works, but we're not seeing all the published works because they were never in the first set to begin with.

**Solution: Up the max_documents parameter to 100_000 and that should fix it.**
