### ISSUE TITLE
"read more" links for field help text

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1156]
# Feature Request

The "hint" text that appears under some field elements (as configured in [`en.yml`](https://github.com/psu-libraries/scholarsphere/blob/42298b892e98edd83eb60db38cd04336edd4c9d8/config/locales/en.yml#L196)) doesn't support arbitrary html or links. This is a problem in cases where we'd like to refer users to additional documentation relating to the field. We should fine a way to allow "read more" links in the hint text. 

*This is blocking #793*

## Describe the solution you'd like

I can think of two approaches:

- interpret the `helpers.hint` values in `en.yml` as markdown or html and add links when necessary.
- Add new helper for setting a `readmore_url` for a field. If the url is set then a "read more here" links is added to the end of the hint text.

I think I prefer the first option but I could be convinced otherwise.

**Comment by rschenk** [comment]
@srerickson There are a few ways we can do this. Within the form controls that we've made components for (which, I think, is most of them) we have complete control over how these fields coming from `en.yml` are interpreted. 

Example:
```erb
  <% if has_hint %>
    <small id="<%= hint_id %>" class="form-text text-muted"><%= t(hint_i18n_key) %></small>
                                                                ^^^^^^^^^^^^^^^^
  <% end %>

```

The easiest scenario would simply be to allow HTML in the en.yml file for these entries, and render it into the form template verbatim. There's no risk of injection attacks there because the en.yml file is part of our source and not user-submitted data. The downside of doing that is, if you made a syntax error in that HTML, then you could bork the entire site without knowing it. 

We could add markdown support to these fields in en.yml as well. It would be mildly more effort than HTML but not tremendously so.

What do you reckon?

**Comment by rschenk** [comment]
Example of raw HTML in en.yml file:

```yml
  helpers:
    hint:
      editors_form:
        edit_users: Requires the user's Penn State Access ID (e.g., xyz500) <a href="https://google.com">This is a link to google</a>
```

![Screen Shot 2022-01-17 at 2 46 59 PM](https://user-images.githubusercontent.com/14730/149829388-5cbe56d8-180b-44aa-a6bd-4140b72970db.png)

**Comment by srerickson** [comment]
may regret it later, but I think raw html is fine. Can we include a big scary warning in the `yml`? (I don't see comments there now).

**Comment by rschenk** [comment]
OK we have a few options:

* Make an exception _for form hints only_ that allow either raw HTML or MD to be included in the en.yml file. This would be specific behavior added to the form hint rendering component and would only live there.
* Write a custom plugin for the `I18n` library (which by the way does support plugins) that would render MD on _everything_ in the en.yml file. I have a prototype of this working based on [this code I found](https://github.com/franckverrot/emobility-i18n/blob/master/lib/emobility-i18n/backend/markdown.rb) on github, but it does have some broader issues.

The easiest solution is raw html in the form hints. I believe parsing that as Markdown will only be slightly more effort and will build on top of the work needed for raw html. I do like the markdown syntax better for links and stuff, so I may give that a crack.

**Comment by srerickson** [comment]
@rschenk, I like the first option as well (html/markdown for form hints only). I'm fine with or without markdown.
