### ISSUE TITLE
DOI api endoint should only include Work IDs

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1164]
The API endpoint for looking up resource IDs by their DOI appears to provide IDs of work versions; it should only provide IDs for Works (or Collections). This is a problem for the integration with RMDB since it means the imported links to ScholarSphere will be for versions, not works.

**Comment by nicktiberi** [comment]
@ajkiessl - Seth suggested that this might be a good issue for you to look into since it deals with our integration with RMD.

**Comment by ajkiessl** [comment]
@srerickson I'm going to try to articulate some of the logic for this feature here.  Let me know if this doesn't sounds right.

When someone (or something) hits the DOI Search endpoint, the ideal situation would be that a single DOI is associated with a single UUID.  For a user outside of the system, the UUID allows them to create a url to view the version, work, or collection.  So let's say I am sending a DOI to the endpoint and I expect a single UUID in return...

If that DOI is associated with a WorkVersion, we want to return the UUID of the Work it is associated with.  It looks like the UUID of a Work always renders the most recent published version of the Work when directed to it's url (which is what we want).

If that DOI is associated with a Work, then we just want to return the UUID of that Work (which should render the most recent published version when directed to it's url).

If that DOI is associated with a Collection, then just return the UUID of the Collection.

If that DOI is associated with both a Work and a Collection (or any combination that includes a Collection), then the Collection would take precedence and the Collection UUID should be returned.

If a DOI is associated with both a Work and a WorkVersion (or multiple WorkVersions), then return the UUID of the Work.

I'm assuming that we don't want multiple Works to have the same DOI, or have WorkVersions associated with different Works to have the same DOI, but that this may still happen in rare cases due to human error?

**Comment by srerickson** [comment]
Some general context that may be useful: the DOI endpoint is used to answer questions like: "Is a thing with this DOI already in ScholarSphere? If so, what thing (or things)?" The "things" should always be work or collection resource IDs (not versions). We don't want to present different versions of the same work as distinct "things" in this case.

More below:

> When someone (or something) hits the DOI Search endpoint, the ideal situation would be that a single DOI is associated with a single UUID. For a user outside of the system, the UUID allows them to create a url to view the version, work, or collection. So let's say I am sending a DOI to the endpoint and I expect a single UUID in return...

So far, so good. Note, ideally the DOI will be associated with a single UUID, but the API endpoint doesn't care either way: it should present a list with one or more UUIDs for each DOI, as it currently does. If multiple works have the same DOI, that's something for curators to fix. The API should present all the works that are associated with the DOI.

> If that DOI is associated with a WorkVersion, we want to return the UUID of the Work it is associated with. It looks like the UUID of a Work always renders the most recent published version of the Work when directed to it's url (which is what we want).

I would phrase this differently: "If that DOI is associated with __the most recently published version of a work__, we want .. (etc.)". When it comes to work versions, we should ignore DOIs that may be included in versions other than the most recently published version.

> If that DOI is associated with a Work, then we just want to return the UUID of that Work (which should render the most recent published version when directed to it's url).

Yes.

> If that DOI is associated with a Collection, then just return the UUID of the Collection.

Yes.

> If that DOI is associated with both a Work and a Collection (or any combination that includes a Collection), then the Collection would take precedence and the Collection UUID should be returned.

Not quite. The DOI endpoint doesn't need to determine a preferred UUID in this case. It should return the UUIDs for both the collection and the work.

> If a DOI is associated with both a Work and a WorkVersion (or multiple WorkVersions), then return the UUID of the Work.

Yes, however, this is an unlikely case because the only DOIs that are already part of the Work are those minted by ScholarSphere. Someone would have to mint the DOI and *also* enter it as the DOI in the work version for this to happen. Seems unlikely, but possible.

> I'm assuming that we don't want multiple Works to have the same DOI, or have WorkVersions associated with different Works to have the same DOI, but that this may still happen in rare cases due to human error?

If multiple works have the same DOI, that's something for curators to fix. The API should present all the works that are associated with the DOI. For WorkVersions, because there is a 1:1 correspondence between the work and the most recently published work version, it's the same as for Works. 

Hope that's helpful!

**Comment by srerickson** [comment]
In retrospect, I think the key details that needed to be added to this issue are:

- We should ignore DOIs in versions other than the most recently published version of a work.
- Instead of showing the UUID for work version in the API, show the UUID for the work.
