### ISSUE TITLE
Problem adding works to a collection

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1249]
# Bug Report
>  I'm in the process of uploading individual research posters into ScholarSphere and then adding each work into the Stuckeman School Research Open House collection. I've added 50 works into the collection, but I'm unable to add any additional works.  Are collections capped at 50 works?  

# Steps from user report:

1- Create and publish a work
2- Go to my dashboard and scroll until I find the entry for the collection
3- Click on Update Collection
4- Click on Works
5- Scroll to bottom of list of works to the 'Add works to the collection' box
6- Click on the down arrow in the box to reveal the title of the work that I just published
7- Scholarsphere shows the list of works I published that are not yet in a collection
-- although the work is published (I double checked), it does not show up in the box.  Instead, I receive this:  "No results found"

**Comment by nicktiberi** [comment]
Ack - I bet I know why this is happening. After releasing #1194, we now limit the max results in the works dropdown to 50 (previous value was 10000). I incorrectly assumed that no normal user would have more than 50 works.

If all of the first 50 works are in the collection, they get filtered out on the frontend and it looks like no more works are available. 

I bet if the user started typing the title for this work, it would eventually appear because at that point we would be doing a new Solr search, filtering the results on title. 

A quick fix would be to raise this limit to some number that no normal user would be likely to exceed. Maybe we 10x it to 500? What do you think, @srerickson?

**Comment by nicktiberi** [comment]
We might also be able to change the text to say something more helpful than just "No Results Found".

**Comment by srerickson** [comment]
@nicktiberi, so I understand, if the user entered a query in the box, they would see the work in the results, correct? In other words, we were assuming people would type something in the search box, but this user isn't doing that. Do I have this right?

**Comment by nicktiberi** [comment]
Pretty much, yes. If all the works from the unfiltered Solr query (i.e. nothing typed in the search box) were already in the collection, then the user would see "No Results Found". If they started typing, they would see results, but only if the results of that new, filtered Solr query returned works that were not already in the collection.

In thinking about this a bit more, it may also be possible to pass an array of work IDs to exclude from the Solr results, so the initial 50 works returned by the query would exclude works already in the collection. Then we wouldn't have to do the JavaScript filtering and wouldn't have this problem, regardless of the max number of returned results.

**Comment by nicktiberi** [comment]
To further clarify, currently there are 2 levels of filtering:

1. on the Solr end, we are filtering the works by title (what the user types into the search box)
2. on the frontend, we use JavaScript to filter out any works we get from Solr that may already be in the collection
