### ISSUE TITLE
Work settings when creating first versions.

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1261]
# Feature Request
On the "review and publish" page of the work submission form, you can set Penn State or Public access. This is a "work setting" that really only makes sense on the first version of a work (we disabled changing access from Public to Penn state once a version is published - see #1204). In addition, it would make sense to allow users to configure other "work settings" when depositing the first version of a work. After deposit, these settings can be managed through the "work settings" page.

- [x] The Penn State/Public access field should only appear for v1 draft works.
- [ ] Add embargo field (same UI as Work Settings Page) below the Access field in "Work Details". This  field should only appear for v1 draft works. Hint text: "Files will be restricted until after the embargo date. When the embargo lifts, files may be accessed based on the access settings above."
- [ ] Add checkbox: "Create DOI on Completion" that, when checked, causes a DOI to be be minted for the work *when the first version is published*.  This field should only appear for v1 draft works. Hint text: "Do not create a DOI if another publisher or repository has already assigned one. [Read more](https://docs.scholarsphere.psu.edu/guides/deposit-overview/#assigning-a-doi)"

**Comment by rschenk** [comment]
Adding the embargo to the Review And Publish page presents some problems because the `embargoed_until` field is stored as a datetime, but must be presented to the user as a date in a plain text field. When the user submits that field, it must be first parsed and casted to a date, then ultimately converted to midnight of that day before being written to the database. There are two validations that need to be checked: that the string is in the correct format (e.g. "2022-03-09" and not "9/3/22") and that the date is actually valid (e.g. not "2022-02-30").

Typically Rails gets around some of these problems by using select boxes for dates/times, and/or using javascript datepickers. For some reason we chose not to use these options in other parts of the app, I think because of accessibility concerns.

Right now the Work Settings page does all the heavy lifting described in the first paragraph by using a form object, but this approach cannot be used on the Review And Publish page because it uses the Work and WorkVersion models directly without a form object sitting in the middle. Therefore we have a few options to add the embargoed_until field on this page now..

**Option 1, punt.** Don't do it because it's not currently worth the effort.

**Option 2, JS datepicker.** Find an accessible js datepicker and us it to handle all the display formatting issues, and submit the params back to Rails using the special format that Rails understands for dates.

**Option 3, Virtual Attributes.** Define a `embargoed_until_display` method on the Work model that returns a formatted string ("2022-03-09"). Define a `embargoed_until_display=` method that will parse the string, and if valid set the actual `embargoed_until` attribute. Duplicate the date validations from the work settings embargo form. Then refactor the work settings embargo form to use this new attribute instead of doing the above logic itself, which DRYs up the code and makes the work settings embargo form a thin wrapper.

**Option 1,000 mega refactor.** This will be necessary for Seth's future plans for the Pathways concept. Instead of the work form using the Work and WorkVersion models directly, make each page in that form be its own form object, with validations and attributes concerning only what's present on that page. As a result, some of the validations might need to be removed from the Work and WorkVersion models entirely, which could have impacts on the API. That's not a deal breaker, but something to keep in mind while doing this.

**Comment by banukutlu** [comment]
just fyi @srerickson initial draft access fields and mint doi checkbox is actually ready for review on https://scholarsphere-oai-pmh.dsrd.libraries.psu.edu/

note: I could not find a way to actually have a work that will generate a doi successfully, so far with my test it always tries to generate then cannot. Minting doi on completion is being handled async so I was not sure how to handle the reporting back the result.

**Comment by srerickson** [comment]
@banukutlu, thanks! If DOI minting isn't working in QA, then we probably should remove that functionality for now. I wonder if the DOI errors have to do with the DataCite configuration being used in QA? @whereismyjetpack any thoughts?

**Comment by whereismyjetpack** [comment]
yeah, it tried but bombed out. probably a misconfigured password or prefix 


```


DataCite::Client::Error: [{"status"=>"403", "title"=>"You are not authorized to access this resource."}]
--
```

**Comment by srerickson** [comment]
I can confirm that the test credentials used in QA are correct. I was able to create a DOI from the command line using curl. I did encounter the error above ("unauthorized to access this resource") when I tried to create a DOI using the wrong prefix, so that may be the problem here. (You get a different error when the credentials are bad).

@banukutlu, you might check that the correct DOI prefix is being used when DOIs are created ~~in QA~~ on preview branch. the `DATACITE_PREFIX` environment variable has the correct value. In production it's 10.26207, but in QA it should be 10.33542.

**Comment by srerickson** [comment]
Another mystery: the failed DOI minting operations don't seem to appear in Sidekiq's dead jobs list.

**Comment by whereismyjetpack** [comment]
they do on this deploymetnt https://scholarsphere-oai-pmh.dsrd.libraries.psu.edu/, it's using the same credentials as qa. i'm not sure we've minted a doi in qa in awhile

**Comment by srerickson** [comment]
minting DOIs on ~~QA~~ the preview branch through works settings appears to [work ok](https://scholarsphere-oai-pmh.dsrd.libraries.psu.edu/resources/5878025b-f917-415a-9814-7676fd39e6c4).

**Comment by whereismyjetpack** [comment]
It looks like the doi is getting minted properly, but not being indexed or something, probably a race condition 

```
WorkVersion.last.doi
=> "10.33542/bb7t-j612"`
``

**Comment by whereismyjetpack** [comment]
I think this is a work / work version thing

look at this work 
https://scholarsphere-oai-pmh.dsrd.libraries.psu.edu/resources/e15c17ca-a8f3-49

```
irb(main):001:0> WorkVersion.last.doi
=> "10.33542/bb7t-j612"
irb(main):002:0> Work.last.doi
=> "10.33542/x42h-gz96"
```

**Comment by whereismyjetpack** [comment]
the work DOI was minted in the UI, and the workversion one, i believe, was minted on creation.

**Comment by srerickson** [comment]
@banukutlu, it's probably not realistic to fix the DOI issue before next week, but is there any chance to include the "Penn State/Public access field should only appear for v1 draft works" functionality in the upcoming release? (We can add the DOI checkbox later).

**Comment by banukutlu** [comment]
> @banukutlu, it's probably not realistic to fix the DOI issue before next week, but is there any chance to include the "Penn State/Public access field should only appear for v1 draft works" functionality in the upcoming release? (We can add the DOI checkbox later).

yes agreed on the doi checkbox and yes we can just move the access fields changes forward and keep the rest out. I will make a PR with access fields changes only.

**Comment by banukutlu** [comment]
Just fyi, I added a PR that only has the access fields changes.
