### ISSUE TITLE
Customized forms for the Data & Code Pathway

### ISSUE THREAD

**Issue by bdezray** [psu-libraries/scholarsphere#1469]
Fields for this pathway are listed below. In our current set up the creators are added in their own form and the embargo date occurs during the work settings. It may be useful to consider moving the embargo setting somewhere in the deposit form.  
Work Title (Required)
Work Type (Required)
Description (Required)
Publication Date (Required)
Subtitle (Optional)
Keyword(s) (Optional)
Publisher (Required) -> should this be set to ScholarSphere automatically?
Related URLs (Optional)
Geographic Area (Optional)
Funding Reference (Optional)
Subject (Optional)
Language (Optional)
Source (Optional)
Semantic Version (Optional)
Creator (Required)
Depositor (Required)
Embargo Date (Optional)
Version (Optional)
License (Required)

Additional features for this pathway:
- Curation request when work is in draft status prior to publication. This would result in the following options for the depositor:
1. Review and then publish (recommended): Curators will review your submission before it is published. A draft DOI can be requested before data is reviewed. The dataset is not published until curation is complete and the submitter is ready for the files to be public.   Include some sort of recognition (badge/message) that the work went through curatorial review. 
2. Publish then review: Data/code is self-submitted to the repository and is immediately public. A working DOI can be requested after you complete your submission. Note, because curatorial review occurs after publication, any changes or updates may result in a new version.  

- Disable Penn State Only Access

**Comment by EricDurante** [comment]
@bdezray,
I have a couple of questions about the form fields for this pathway.

1. There's a note above about possibly setting the publisher field to "ScholarSphere" automatically. Do we indeed want to do that? If so, should the depositor be able to change this? Specifically, since this is a multi-value field, should the depositor be able to remove the "ScholarSphere" value that is automatically set? Should they be able to add more values in addition to "ScholarSphere"?
2. I see that "Funding Reference" is listed as one of the optional form fields, but this isn't a field in the existing deposit forms. So I just wanted to confirm that this is indeed a new field that should be added to work versions. If that's the case, then kind of value(s) would go in this field? Would it be another multi-value string field like keywords, for example?

**Comment by EricDurante** [comment]
@bdezray 
Another question here with regard to "Disable Penn State Only Access":

If a work is subject to the Data & Code pathway, are there any circumstances at all in which the work could not be open access? Put another way - should it ever be possible for a work with type 'Dataset' or 'Software Or Program Code' to be saved with any type of access other than 'Public'?

**Comment by bdezray** [comment]
@EricDurante 

**There's a note above about possibly setting the publisher field to "ScholarSphere" automatically. Do we indeed want to do that? If so, should the depositor be able to change this? Specifically, since this is a multi-value field, should the depositor be able to remove the "ScholarSphere" value that is automatically set? Should they be able to add more values in addition to "ScholarSphere"?**

After further consideration, please ignore this request. So, no need to set the publisher automatically. I think that we have accounted for this through the addition of the citation. 

**I see that "Funding Reference" is listed as one of the optional form fields, but this isn't a field in the existing deposit forms. So I just wanted to confirm that this is indeed a new field that should be added to work versions. If that's the case, then kind of value(s) would go in this field? Would it be another multi-value string field like keywords, for example?**

Yes, this is a field that we were hoping to add. Ideally, we would use the Crossref Open Funder Registry to provide users with a controlled vocabulary for funders to select from that would also bring in the funder identifiers. However, we will likely need to have a way for users to include funders not listed and to as you describe add multiple funders. Let me know if you want to chat about this further!

[Crossref Open Funder Registry Description](https://www.crossref.org/services/funder-registry/)
[Crossref Funder Registry Taxonomy](https://gitlab.com/crossref/open_funder_registry)

Also, if useful and for reference, here is how DataCite breaks down this funder information: [You will need to search for "funder" to get the relevant metadata fields](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties)

**If a work is subject to the Data & Code pathway, are there any circumstances at all in which the work could not be open access? Put another way - should it ever be possible for a work with type 'Dataset' or 'Software Or Program Code' to be saved with any type of access other than 'Public'?**

Ideally, the only instance where these types would not be 'Public' would be if an embargo were placed on the work or if the work was withdrawn or deleted.

**Comment by EricDurante** [comment]
@bdezray 

> Yes, this is a field that we were hoping to add. Ideally, we would use the Crossref Open Funder Registry to provide users with a controlled vocabulary for funders to select from that would also bring in the funder identifiers. However, we will likely need to have a way for users to include funders not listed and to as you describe add multiple funders. Let me know if you want to chat about this further!

Thanks! I'll dig into this and see what other questions I have.

> Ideally, the only instance where these types would not be 'Public' would be if an embargo were placed on the work or if the work was withdrawn or deleted.

I think that the embargo and the withdrawn/deleted status each control the visibility independently of the visibility setting and that those two things essentially override the visibility setting. So it kind of sounds like it's ok for the visibility setting to always be 'Public' for new data & code works. However, I also wonder about existing works. There may be existing datasets and code where the depositor has already set the access to "Penn State Only". If these works are edited and resaved (by anyone - the depositor, an admin, etc.) should the access automatically be changed to "Public" no matter what? The existing rules for how access works are super tricky to navigate given my limited understanding, so I want to be sure that I don't end up changing behavior that's going to cause a problem in some other context that I'm not aware of.

**Comment by bdezray** [comment]
@EricDurante That is a good point about previous visibility settings on works. I don't think that we would want to change these, especially since we often cannot get in touch with older depositors. If it seems like the access controls component of this pathway is very complicated, it is something we could probably leave as is and address with our guidance. Let me know what you think!

**Comment by EricDurante** [comment]
@bdezray Ok - good to know!

I can probably at least take some incremental steps here. It's easy enough to remove the access settings from the deposit form (and to remove them from the work settings) for data & code works, and that feels like a pretty safe change to me. The problem with _only_ doing that is that a depositor could circumvent our intended rules in the following way:
1. Set the work type to something other than dataset or software
2. Change the access setting to "Penn State Only" and save
3. Change the work type back to dataset or software
4. Publish the work

To prevent this, we'd also need to automatically set the access to "Public" whenever a data & code work is saved, but _not_ if the work has already been published with more restricted access. I can attempt to do this, but it feels like a less safe change since I don't fully understand the implications.

**Comment by bdezray** [comment]
@EricDurante I think your proposed incremental steps will work here! We don't see Penn State only used very frequently and if a depositor does circumvent our intended rules we can work with them during the curation process. Thanks!
