### ISSUE TITLE
"My Dashboard" Page

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#29]
This is a placeholder issue for discussing the page where a user's published and draft works are listed. A mockup for the page is [here](https://docs.google.com/drawings/d/1pFZZfBryOIeTxFHdd9vHF0HyoY6mLHNoCvL-IA5K-mI/edit).

**Comment by rschenk** [comment]
Some of these questions are about the wireframe itself, and others are more general business logic questions that these wireframes bring up, but should probably be spun out into their own issues when they're coded up.

### 1. Creating new deposits
How/where do I make a new deposit?

### 2. Deleting draft versions
If a Deposit has more than one version, then deleting a draft version is simple—just delete the work-version. What about a deposit like "Supplementary Data for 'preseismic..." which only has a single, draft version? What does clicking the delete link do? Delete the entire Deposit?

### 3. Withdrawing a version
In our current model, a published work-version can be withdrawn. Where do we imagine the controls for that process would be? (Doesn't have to be on this screen, but I want to make sure we don't forget about it.)

### 4. Version numbering
_(This could be split into its own feature)_

On this mockup, I see the version numbers are just sequential integers, i.e. (Version 1, 2, 3...). Currently in our data model, we have a `version_name` field on each work-version—this is an optional string field, where presumably the depositor could type something like `"v1.2.3"` or something like that. 

Do we actually want the ability for depositors to specify explicit version numbers, knowing full well that almost nobody besides software enginerds knows what semantic versioning is? (Personally I think this would be a usability quagmire, and am fully in favor of removing the `version_name` field entirely.) If we decided to proceed with a user-editable `version_name` field, I'd like to see some mockups/wireframes that describe the desired view behavior: What happens if some of a work's versions have a value in `version_name` but not all of them? What does it look like if the first two versions of a work, I did not provide a `version_name`, but months later on the third version I decide to type in `"1.0"`? What happens if in one work-version I provide the `version_name` as `"1.2.3"` but in the next one I type `"v1.2.4"` followed by the next one, `"Version 1.3.0"`? Do we need input masking on this field to only allow numbers? Periods? Hyphens? How many versions do we anticipate each work having and is it worth the above can of worms?

**Comment by srerickson** [comment]
My responses:

### .1 Creating new deposits
You're right, users should be able to create new deposits from this page. I've updated the mock-up. It might make sense to think of the first form in the deposit workflow (w/ the title and work type inputs) as a reusable widget that we can placed in different parts of the app. 

### 2. Deleting draft versions
When a user clicks delete on the only version of a work, they should get a prompt:
> You are deleting the only version of this Work. Clicking "continue" will delete 
   all files and metadata associated with this work and remove it from your deposits.
  [continue] [cancel]

### 3. Withdrawing a version
I had "withdraw" as an action next to published versions in an early version of the mock-up, but then I got to thinking: I feel like this feature will be abused by users. The administrative ability to withdraw works is a must but I don't think we need to foreground this to users. I think it's something users should ask administrators/curators to do.  (and ideally we can do it with some command line client ;-). Withdrawn works would still appear on this list—just with the label "withdrawn" instead of published. If the last version of a work is withdrawn you can still base a new version off of it.

###  4. Version numbering
I forget if we had a use case for "version names"—I expect not. My preference is to refer to versions by their sequential number.

**Comment by rschenk** [comment]
Sounds good to me, I'll update my original post with the answers so they're all together

**Comment by DanCoughlin** [comment]
Is "My Deposits" include both your deposits and what you have edit access to? Default view will be only the objects you have uploaded, with a filter to see all deposits that included edit access to.

Administrators can be given a view to see other works within the system to edit that data. It may be helpful to implement a two views that list works the same, but have different facets
View 1 is for a My Depositor view with filters or facets such as
1- My Deposits
2- Works that I've collaborated on with an administrator because they have been given edit access (if use is an administrator)
3- All Works in the system that I have access to
View 2 is for a Generic Search Interface with a different set of facets

**Comment by srerickson** [comment]
The idea we discussed in the kickoff is that the "My deposits" should reuse the same general interface pattern of the generic search page, with a few changes:

- The facets for filtering works would be oriented around users relationship to the work (depositor, creator, edit access, etc.)
- Listed works may be in a draft state/unpublished.
- The "Create New Work" widget for kicking-off the deposit process should also be on on the page. 

Relates to wireframes by @monksp : https://github.com/psu-stewardship/scholarsphere-4/issues/207#issuecomment-603253442

**Comment by DanCoughlin** [comment]
Need to discuss the facets a bit, starting point is to be able to filter files based on:
- Created it 
- Edit Access 
- Listed as an author
