### ISSUE TITLE
Investigate 404 errors

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#747]
Redirects to published works from SS3 should (ideally) not 404.

## WDLL

* count links like `/concern/generic_works/[id]` and redirect with a 200
* count links like `/concern/generic_works/[id]` and redirect with a 404
* create custom widget in Splunk

**Comment by whereismyjetpack** [comment]
i've created a report that shows all the hits to the LegacyUrlsController that ultimately returned a non-200 status. I'm creating a widget on the dashboard that contains the same data. 

The attached file is a txt file, because that's what GitHub supports, if you open it up in numbers, or excel it should format properly. 

Interesting thing of note, all the requests over the last 14 hours that got a 404 threw `Pundit::NotAuthorizedError: not allowed to show? this WorkDecorator` I, as an admin still can't visit the resolved link, i'm hoping it's something easy to fix. 


[1606845011_839_2857FFD7-2774-4137-A7E5-8D056B663985.txt](https://github.com/psu-stewardship/scholarsphere/files/5624472/1606845011_839_2857FFD7-2774-4137-A7E5-8D056B663985.txt)

**Comment by awead** [comment]
@whereismyjetpack That's the correct response. Technically, it's a 401 because they're not authorized to view the resource, but we don't want to give away it's existence. This is likely because a work that was formerly open access in Scholarsphere 3 is missing some required metadata in version 4, so it still in draft status, and thus, not viewable.
