### ISSUE TITLE
Rethinking the authorship model

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#814]
## How we handle authorship now

Our current data model involves a list of people ("actors") who are linked to works through a join table (see the schema code below). To add an author to a work, we do the following (in principle): 

1. Check if the "actor" already exists in the actors table or PSU directory, 
2. Create the actor if they don't exist in the actors table (potentially using info from PSU directory).
3. Add an entry to the join table, linking the actor and the work (version).

To help with step (1), we have some identifiers (`psu_id`, `orcid`), but there are a lot of "actor" entries without them. Further, the UI doesn't *require* you to use one of these identifiers in step (1); The UI makes it easy to *treat the name as an identifier* here, which is an anti-pattern (names aren't unique to a person and a person can have multiple names).  An actor entry consisting only of a name is inherently ambiguous.

We've started to require identifiers (at the UI-level) when actors are created (step 2). Unfortunately, authors may not have one of the identifiers we require (ORCID or PSU ID), so we're not able to input complete authorship information for some works. On the database side, we could, in principle, create new actor records without these identifiers, but doing so would further entrench the anti-pattern described above.

```rb
  # db/schema.rb
  # here's how we store author information
  create_table "actors", force: :cascade do |t|
    t.string "surname"
    t.string "given_name"
    t.string "email"
    t.string "psu_id"
    t.string "orcid"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.string "default_alias"
    t.index ["orcid"], name: "index_actors_on_orcid", unique: true
    t.index ["psu_id"], name: "index_actors_on_psu_id", unique: true
  end

  # here's how we store link between authors and works (work versions).
  create_table "work_version_creations", force: :cascade do |t|
    t.bigint "work_version_id", null: false
    t.string "alias"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.bigint "actor_id", null: false
    t.integer "position"
    t.index ["actor_id"], name: "index_work_version_creations_on_actor_id"
    t.index ["work_version_id"], name: "index_work_version_creations_on_work_version_id"
  end
```

## Desirable new features

- (A) Actors without identifiers (PSU or ORCID) shouldn't appear as "results" when searching for existing actors (step 1, above). This would prevent the use of actor entries that are impossible to disambiguate.  (Bonus: we should use both ORCID *and* the PSU directory to search for existing actors).
- (B) It should be possible to add an author to a work without an identifier. (How we represent these "ambiguous authors" in the database is an open question).

## Proposal

I don't have a full fledged proposal right now, just some thoughts. I'd like to discuss it more, but it seems that features A and B (above) are kind of contradictory under our current data model. This suggests we need some way to create "authors" that aren't full fledged (i.e., identified) actors.

**Comment by awead** [comment]
@rschenk and I talked about this briefly this morning and came up with two solutions. The "bad actors" or the ones without identifiers came from Scholarsphere 3, and they'll always be there. So the the general idea is that we should do as much as we can to ensure we have some kind of unique identifier for an actor, access id, ORCID, or otherwise, but that it should not preclude someone from being added.

So the strategy then is how can we better organize that.

## Option 1: Use a separate table

In this solution, off-load the non-identified actors to a separate table and make WorkVersionsCreations into a polymorphic association. It points to both Actor and BadActor tables. This keeps everything pretty well separated, and the join table can allow the user order each actor type interchangeably. Both bad and good actors can co-mingle freely.

## Option 2: Sub-class Actor with the same table

This leans on a more Ruby approach. We create a new class, like BadActor, and point it to the same table. This allows us to define different validation criteria, such as no identifiers required, and to better distinguish between the two types at the application layer.

Both options have their pros and cons. The deciding factor would probably be metadata. If there's no distinction in attributes between the two actor types, we can probably go with option 2. We can determine the actor type based on the presence of an identifier, or add a new column to the table the defines the type explicitly.

One question: Under _Desireable new features_ (A), if we don't allow users to choose existing actors without identifiers, then we run the risk of having duplicate entries for identical people. But, I do understand that adding unidentified actors to new works is probably not a good idea.

Tangential to this issue is #685, which affects searching for existing actors, but also affects faceting. We should probably consider fixing this issue as well so that we can add middle names or initials to better differentiate between both known and unknown actors alike.

**Comment by srerickson** [comment]
I was thinking something like the following, which would involve de-normalizing actor records that have no identifiers, migrating the names into the join table.

```rb
  # actors is basically just identifiers 
  create_table "actors", force: :cascade do |t|
    t.string "psu_id"
    t.string "orcid"
    t.string "full_name"   # <--- just to display results, like a cache from PSU Directory or Orcid.
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["orcid"], name: "index_actors_on_orcid", unique: true
    t.index ["psu_id"], name: "index_actors_on_psu_id", unique: true
  end

  # author name stuff moved into the join table.
  create_table "work_version_creations", force: :cascade do |t|
    t.bigint "work_version_id", null: false
    t.string "surname"               # <-- move all author info into the join
    t.string "given_name"
    t.string "alias"
    t.string "email"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.bigint "actor_id"        # <-- can be null!
    t.integer "position"
    t.index ["actor_id"], name: "index_work_version_creations_on_actor_id"
    t.index ["work_version_id"], name: "index_work_version_creations_on_work_version_id"
  end
```

It's just an idea -- perhaps a bad one.

**Comment by srerickson** [comment]
Responding to the question: 

> Under Desirable new features (A), if we don't allow users to choose existing actors without identifiers, then we run the risk of having duplicate entries for identical people. But, I do understand that adding unidentified actors to new works is probably not a good idea.

Yes, that's true and I'm ok with that kind of duplication (i.e., of name strings). The way I see it, we don't "have" an entry for a person if there's no identifier associated with the actor record. What could happen is we end up with two entries for the same person, one using psu_id and another using orcid: in that situation we can merge records as they're identified. The point is that they *can* be unambiguously identified.

**Comment by awead** [comment]
## Conclusion

After a meeting on Jan 18, we've arrived an initial solution based on Seth's above proposal. Actors that have no identifier (either Penn State or Orcid) will be removed from the Actor table and have their remaining metadata such as given and family names, and email, copied to the WorkVersionCreations table. This represents about two-thirds of the actors in the table, however, many of these unidentified actors are duplicates.

## Results

* authorship bibliographic citation information becomes the domain of `WorkVersionCreations`
* any author can be added to a work (Feature B)
    * _if_ the author can be identified, they will have a linked record to the `Actor` table with their identifiers
    * unidentified authors have no linked Actor record
    * both types of authors can exist as a sorted list in a work
* authorship metadata is separate: changing the name of an author in `WorkVersionCreations` requires a new version but changing the name in the `Actor` table leaves existing publications unaffected
* searching for existing authors can only come form the Actor table, or other vetted sources such as Penn State's identify service or Orcid. (Feature A)

## Details

The underlying structure of the database will basically remain the same, however, the metadata and fields will be moved around a bit. The structure and experience of the UI will initially remain the same as the new backend changes are made, but soon after, the UI will change to better reflect the the new creator/author model.

All the technical details will be outlined in #817.
