### ISSUE TITLE
Inconsistency between access setting that appears on the catalog page and the work page. 

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#955]
On the catalog, a work appears to have Penn State-only access [[link](https://scholarsphere.psu.edu/catalog?search_field=all_fields&q=Acceptability+of+electronic+nicotine+delivery+systems+%28ENDS%29+among+HIV+positive+smokers)]. However, the work actually is public [[link](https://scholarsphere.psu.edu/resources/c2ad3853-93d2-44c2-9098-521972c4f6a6)]. Looks like the setting was updated without a re-index?

**Comment by awead** [comment]
I tried toggling from Penn State back to Open in the work settings page, but the search result is unaffected. It could be that when saving the work from the settings page, Solr isn't getting indexed. Note that changing the visibility setting in the work form _will_ trigger a re-index. I've verified this in QA with a work that's already been published. However, we shouldn't do this in production because it will add a record to the paper trail changes.
