### ISSUE TITLE
Managing UMG edit groups

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#956]
# Feature Request

## Describe the solution you'd like

We should see a list of the current groups that have edit access to a resource. Presently, there's just an multi-select form and you'd only know if a group was there if _you_ the logged in users where a member of it.

## What does "done" look like?

A listing of current UMG groups that have edit access, probably above the select box? UI design is up for discussion.

**Comment by ajkiessl** [comment]
It'd be helpful if admins could remove these groups.  Whatever we decide for the UI design, it should allow the admins to at least remove the groups already assigned to the resource that the admin may not have access to add.

**Comment by ajkiessl** [comment]
We should consider the future of the "Groups" feature and how much of it we want to keep.   We seem to mostly get complaints about users seeing things they don't want to see in their dashboards, rather than users actually benefiting from the feature.  Our general access policies (like Open Access, Restricted, etc.) are defined using the Group model, so we can't remove everything related to groups.  Perhaps we can find a way to get rid of the things that cause issues.  Like the `starfish` group and other UMGs.

As far as I know, allowing users to add specific users to edit a work is all they really need.  No need to have group level access controls.

**Comment by Smullz622** [comment]
Update after discussion with Alex:

For now, we will leave the existing select box form show for regular users but have an add/remove form show for admins. There still needs to be discussion about the future of umg groups and whether we will let regular users do anything with them, but this will solve the immediate problem that admins need a way to remove unwanted umg groups.
